# GitHub Sponsors
github: [quantumshiro]

# Patreon
patreon: quantumshiro

# Ko-fi
ko_fi: quantumshiro

# Buy Me a Coffee
buy_me_a_coffee: quantumshiro

# カスタムURL（プロジェクトのウェブサイトやドネーションページなど）
custom: ['https://polytorus.com/']
