# Production Docker Compose with secrets support
version: '3.8'

secrets:
  db_password:
    external: true
  redis_password:
    external: true

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: polytorus
      POSTGRES_USER: polytorus
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - polytorus-internal
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polytorus"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass-file /run/secrets/redis_password --appendonly yes
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    networks:
      - polytorus-internal
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  polytorus:
    image: polytorus:latest
    environment:
      POLYTORUS_NODE_ID: node-prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: polytorus
      DB_USER: polytorus
      DB_PASSWORD_FILE: /run/secrets/db_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      RUST_LOG: info
    secrets:
      - db_password
      - redis_password
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - polytorus-network
      - polytorus-internal
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  postgres_data:
  redis_data:

networks:
  polytorus-network:
    driver: overlay
    external: true
  polytorus-internal:
    driver: overlay
    internal: true
