# Kani Configuration for Polytorus Blockchain Verification

# Global configuration
[verification]
# Set strict bounds for verification to prevent timeout and unwinding issues
unwind = 20        # Further reduced to prevent memcmp unwinding issues
timeout = 300      # Increased timeout to accommodate verification complexity
# Ignore global assembly to work around wasmtime-fiber issue
ignore-global-asm = true
# Limit memcmp and memory operations unwinding with more aggressive settings
solver-args = ["--unwind", "20", "--bounds-check", "--pointer-check", "--no-unwinding-assertions", "--memcmp-unwind", "5"]

[verification.crypto_verification]
description = "Formal verification of cryptographic operations"
harnesses = [
    "verify_ecdsa_sign_verify",
    "verify_fndsa_sign_verify", 
    "verify_transaction_integrity",
    "verify_merkle_tree_properties"
]

[verification.blockchain_verification]
description = "Formal verification of blockchain operations"
harnesses = [
    "verify_block_hash_consistency",
    "verify_difficulty_adjustment",
    "verify_mining_stats",
    "verify_verkle_tree_operations"
]

[verification.transaction_verification]
description = "Formal verification of transaction processing"
harnesses = [
    "verify_transaction_signing",
    "verify_utxo_consistency",
    "verify_contract_transaction_integrity"
]

# Global verification settings
[solver]
engine = "cbmc"
unwinding = 20
memcmp-unwind = 3     # Drastically limit memcmp loop unwinding
string-unwind = 3     # Limit string operation unwinding

[restrictions]
function_call_limit = 20    # Further reduced to prevent deep call stacks
loop_unroll = 3             # Minimal loop unrolling
max_memory_compare = 16     # Severely limit memory comparison operations
max_array_size = 128        # Limit array sizes to prevent excessive memory operations
