[package]
name = "polytorus-kani"
version = "0.1.0"
edition = "2021"
description = "Kani formal verification for Polytorus core functions"

[lib]
path = "src/lib.rs"

[dependencies]
# No runtime dependencies needed for Kani verification
